# -*- coding: utf-8 -*-
"""FaceNet (Testing Purposes)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10eobZ1rIvZe9S-0s_GXQ9J2Mn8CjbL0C
"""

!pip install -q keras-facenet mtcnn opencv-python

from google.colab import drive
drive.mount('/content/drive')

import json
import pickle
from pathlib import Path

import cv2
import numpy as np
from keras_facenet import FaceNet

BASE_DIR = Path("/content/drive/MyDrive/Capstone")

# Nathan training folder
TRAIN_DIR = BASE_DIR / "dataset" / "nathan"

# Folder you want to test
# Change this to "normal", "dark", or "glasses"
TEST_SUBDIR = "khoi"
SESSION_DIR = BASE_DIR / "dataset" / TEST_SUBDIR

# Metadata file for that session
METADATA_FILE = SESSION_DIR / "metadata.json"

# Output folder
MODEL_DIR = BASE_DIR / "model" / "facenet"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

AUTHORIZED_EMBEDDINGS_FILE = MODEL_DIR / "authorized_embeddings.json"

# FaceNet threshold
THRESHOLD = 0.90

embedder = FaceNet()

CASCADE_PATH = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
face_detector = cv2.CascadeClassifier(CASCADE_PATH)

if face_detector.empty():
    raise RuntimeError(f"Could not load Haar cascade: {CASCADE_PATH}")

def detect_largest_face(image_bgr):
    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

    faces = face_detector.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(80, 80)
    )

    if len(faces) == 0:
        return None

    faces = sorted(faces, key=lambda f: f[2] * f[3], reverse=True)
    return faces[0]


def crop_face(image_bgr, face_box, padding=0.20):
    x, y, w, h = face_box
    img_h, img_w = image_bgr.shape[:2]

    pad_w = int(w * padding)
    pad_h = int(h * padding)

    x1 = max(0, x - pad_w)
    y1 = max(0, y - pad_h)
    x2 = min(img_w, x + w + pad_w)
    y2 = min(img_h, y + h + pad_h)

    face = image_bgr[y1:y2, x1:x2]

    if face.size == 0:
        raise ValueError("Face crop was empty")

    return face


def get_embedding(face_bgr):
    face_rgb = cv2.cvtColor(face_bgr, cv2.COLOR_BGR2RGB)
    emb = embedder.embeddings([face_rgb])[0]
    emb = np.asarray(emb, dtype=np.float32)

    norm = np.linalg.norm(emb)
    if norm == 0:
        raise ValueError("Embedding norm was zero")

    return emb / norm


def compare_embedding(query_embedding, known_embeddings_dict):
    best_name = None
    best_distance = float("inf")

    for name, stored_embedding in known_embeddings_dict.items():
        known_embedding = np.asarray(stored_embedding, dtype=np.float32)

        # supports either one embedding or a list of embeddings
        if known_embedding.ndim == 1:
            distances = [float(np.linalg.norm(query_embedding - known_embedding))]
        else:
            distances = [
                float(np.linalg.norm(query_embedding - emb))
                for emb in known_embedding
            ]

        distance = min(distances)

        if distance < best_distance:
            best_distance = distance
            best_name = name

    return best_name, best_distance

nathan_embeddings = []

valid_exts = {".jpg", ".jpeg", ".png"}

for image_path in sorted(TRAIN_DIR.iterdir()):
    if image_path.suffix.lower() not in valid_exts:
        continue

    image = cv2.imread(str(image_path))
    if image is None:
        print(f"[WARN] Could not read {image_path}")
        continue

    face_box = detect_largest_face(image)
    if face_box is None:
        print(f"[WARN] No face found in {image_path}")
        continue

    try:
        face = crop_face(image, face_box)
        emb = get_embedding(face)
        nathan_embeddings.append(emb.tolist())
    except Exception as e:
        print(f"[WARN] Failed on {image_path}: {e}")

if len(nathan_embeddings) == 0:
    raise RuntimeError("No usable Nathan training images found.")

authorized_embeddings = {
    "Nathan": nathan_embeddings
}

with open(AUTHORIZED_EMBEDDINGS_FILE, "w") as f:
    json.dump(authorized_embeddings, f, indent=2)

print(f"Saved {len(nathan_embeddings)} Nathan embeddings to:")
print(AUTHORIZED_EMBEDDINGS_FILE)

with open(METADATA_FILE, "r") as f:
    metadata = json.load(f)

with open(AUTHORIZED_EMBEDDINGS_FILE, "r") as f:
    known_embeddings = json.load(f)

print("Session:", metadata["session"])
print("Rounds:", len(metadata["rounds"]))
print("Authorized users:", list(known_embeddings.keys()))

def resolve_to_session_file(image_path_str):
    filename = Path(image_path_str).name
    return SESSION_DIR / filename

def predict_authorized(image_path):
    image = cv2.imread(str(image_path))
    if image is None:
        return {
            "authorized": False,
            "identity": None,
            "distance": None,
            "reason": "could_not_read_image"
        }

    face_box = detect_largest_face(image)
    if face_box is None:
        return {
            "authorized": False,
            "identity": None,
            "distance": None,
            "reason": "no_face_detected"
        }

    try:
        face = crop_face(image, face_box)
        query_embedding = get_embedding(face)
        identity, distance = compare_embedding(query_embedding, known_embeddings)

        authorized = distance < THRESHOLD

        return {
            "authorized": bool(authorized),
            "identity": identity if authorized else "unknown",
            "closest_match": identity,
            "distance": round(distance, 4),
            "threshold": THRESHOLD,
            "reason": "ok" if authorized else "face_not_recognized"
        }

    except Exception as e:
        return {
            "authorized": False,
            "identity": None,
            "distance": None,
            "reason": f"error: {e}"
        }

results = []

for round_info in metadata["rounds"]:
    image_1_path = resolve_to_session_file(round_info["image_1"])

    result = predict_authorized(image_1_path)

    results.append({
        "round": round_info["round"],
        "challenge": round_info["challenge"],
        "image_1": str(image_1_path),
        "authorized": result["authorized"],
        "identity": result["identity"],
        "closest_match": result.get("closest_match"),
        "distance": result["distance"],
        "threshold": result.get("threshold"),
        "reason": result["reason"]
    })

results[:5]

authorized_count = sum(1 for r in results if r["authorized"])
total_count = len(results)

print(f"Folder tested: {TEST_SUBDIR}")
print(f"Authorized passes: {authorized_count}/{total_count}\n")

for r in results:
    print(
        f'Round {r["round"]:03d} | '
        f'{r["challenge"]:10s} | '
        f'authorized={r["authorized"]} | '
        f'identity={r["identity"]} | '
        f'distance={r["distance"]} | '
        f'reason={r["reason"]}'
    )

OUTPUT_FILE = SESSION_DIR / f"facenet_results_{TEST_SUBDIR}.json"

with open(OUTPUT_FILE, "w") as f:
    json.dump(results, f, indent=2)

print("Saved:", OUTPUT_FILE)