# -*- coding: utf-8 -*-
"""FaceNet Liveness Detection (Testing Purposes)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s4vNyI2XvBZNvJaQ74oz2XtuhYq5yxVl
"""

!pip install protobuf==4.25.3 mediapipe opencv-python-headless -q

import mediapipe as mp

mp.solutions.face_mesh
print("working")

# ============================================================
# FaceNet-style Liveness Evaluation for Dataset Rounds
# Works well in Google Colab
# ============================================================

!pip install mediapipe opencv-python-headless numpy pandas -q

import os
import json
import cv2
import math
import numpy as np
import pandas as pd
import mediapipe as mp
from pathlib import Path
from google.colab import drive

# -----------------------------
# 1. Mount Google Drive
# -----------------------------
drive.mount('/content/drive')

# -----------------------------
# 2. CONFIG
# -----------------------------
JSON_PATH = "/content/drive/MyDrive/Capstone/dataset/dark/facenet_results_dark.json"
# change this for glasses/dark later

OUTPUT_CSV = "/content/drive/MyDrive/Capstone/dataset/dark/facenet_liveness_dark_results.csv"
OUTPUT_JSON = "/content/drive/MyDrive/Capstone/dataset/dark/facenet_liveness_dark_results.json"

# thresholds for challenge pass/fail
YAW_THRESHOLD = 0.035      # left/right movement sensitivity
PITCH_UP_THRESHOLD = 0.020 # upward movement sensitivity

# optional minimum confidence that a face exists in both images
REQUIRE_FACE_IN_BOTH = True

# -----------------------------
# 3. MediaPipe setup
# -----------------------------
mp_face_mesh = mp.solutions.face_mesh

face_mesh = mp_face_mesh.FaceMesh(
    static_image_mode=True,
    max_num_faces=1,
    refine_landmarks=True,
    min_detection_confidence=0.5
)

# -----------------------------
# 4. Landmark helper functions
# -----------------------------
def load_image_rgb(path):
    img_bgr = cv2.imread(path)
    if img_bgr is None:
        return None
    return cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

def get_landmarks(image_rgb):
    results = face_mesh.process(image_rgb)
    if not results.multi_face_landmarks:
        return None

    face_landmarks = results.multi_face_landmarks[0]
    h, w, _ = image_rgb.shape

    pts = []
    for lm in face_landmarks.landmark:
        pts.append((lm.x * w, lm.y * h))
    return np.array(pts, dtype=np.float32)

def safe_mean(points):
    return np.mean(points, axis=0)

def estimate_pose_features(landmarks):
    """
    Lightweight face-pose approximation from facial landmarks.
    Returns yaw and pitch style measures using relative landmark geometry.

    Landmark groups:
      left eye outer area
      right eye outer area
      nose tip
      chin
      forehead-ish
    """

    # Mediapipe landmark indices
    LEFT_EYE = [33, 133]
    RIGHT_EYE = [362, 263]
    NOSE_TIP = 1
    CHIN = 152
    FOREHEAD = 10

    left_eye_center = safe_mean(landmarks[LEFT_EYE])
    right_eye_center = safe_mean(landmarks[RIGHT_EYE])
    nose_tip = landmarks[NOSE_TIP]
    chin = landmarks[CHIN]
    forehead = landmarks[FOREHEAD]

    eye_center = (left_eye_center + right_eye_center) / 2.0
    eye_distance = np.linalg.norm(right_eye_center - left_eye_center)

    if eye_distance < 1e-6:
        return None

    # Yaw proxy:
    # compare distance from nose to left eye vs nose to right eye
    dist_left = np.linalg.norm(nose_tip - left_eye_center)
    dist_right = np.linalg.norm(nose_tip - right_eye_center)
    yaw = (dist_left - dist_right) / eye_distance

    # Pitch proxy:
    # compare nose vertical placement between forehead and chin
    face_height = np.linalg.norm(chin - forehead)
    if face_height < 1e-6:
        return None

    pitch = ((nose_tip[1] - forehead[1]) / face_height)

    return {
        "yaw": float(yaw),
        "pitch": float(pitch),
        "eye_distance": float(eye_distance)
    }

def evaluate_liveness_challenge(challenge, pose1, pose2):
    """
    Returns pass/fail and score interpretation.
    """
    if pose1 is None or pose2 is None:
        return False, "pose_estimation_failed", None

    yaw_delta = pose2["yaw"] - pose1["yaw"]
    pitch_delta = pose2["pitch"] - pose1["pitch"]

    if challenge == "LOOK_LEFT":
        passed = yaw_delta < -YAW_THRESHOLD
        score = yaw_delta
        note = "expected more negative yaw change"
    elif challenge == "LOOK_RIGHT":
        passed = yaw_delta > YAW_THRESHOLD
        score = yaw_delta
        note = "expected more positive yaw change"
    elif challenge == "LOOK_UP":
        # when looking up, nose tends to move upward relative to face shape,
        # so pitch proxy typically decreases
        passed = pitch_delta < -PITCH_UP_THRESHOLD
        score = pitch_delta
        note = "expected more negative pitch change"
    else:
        passed = False
        score = None
        note = "unknown challenge"

    return passed, note, {
        "yaw_delta": float(yaw_delta),
        "pitch_delta": float(pitch_delta),
        "raw_score": float(score) if score is not None else None
    }

def derive_image2_path(image1_path):
    """
    Converts:
      ...round_001_img1.jpg -> ...round_001_img2.jpg
    """
    return image1_path.replace("_img1.", "_img2.")

# -----------------------------
# 5. Load test rounds
# -----------------------------
with open(JSON_PATH, "r") as f:
    rounds = json.load(f)

all_results = []

for item in rounds:
    round_num = item.get("round")
    challenge = item.get("challenge")
    image1_path = item.get("image_1")

    if not image1_path:
        all_results.append({
            "round": round_num,
            "challenge": challenge,
            "image_1": None,
            "image_2": None,
            "face_detected_img1": False,
            "face_detected_img2": False,
            "liveness_pass": False,
            "reason": "missing_image_1_path",
            "yaw_delta": None,
            "pitch_delta": None
        })
        continue

    image2_path = derive_image2_path(image1_path)

    img1 = load_image_rgb(image1_path)
    img2 = load_image_rgb(image2_path)

    if img1 is None or img2 is None:
        all_results.append({
            "round": round_num,
            "challenge": challenge,
            "image_1": image1_path,
            "image_2": image2_path,
            "face_detected_img1": False,
            "face_detected_img2": False,
            "liveness_pass": False,
            "reason": "could_not_read_image",
            "yaw_delta": None,
            "pitch_delta": None
        })
        continue

    lm1 = get_landmarks(img1)
    lm2 = get_landmarks(img2)

    face1 = lm1 is not None
    face2 = lm2 is not None

    if REQUIRE_FACE_IN_BOTH and (not face1 or not face2):
        all_results.append({
            "round": round_num,
            "challenge": challenge,
            "image_1": image1_path,
            "image_2": image2_path,
            "face_detected_img1": face1,
            "face_detected_img2": face2,
            "liveness_pass": False,
            "reason": "no_face_detected_in_one_or_both_images",
            "yaw_delta": None,
            "pitch_delta": None
        })
        continue

    pose1 = estimate_pose_features(lm1) if lm1 is not None else None
    pose2 = estimate_pose_features(lm2) if lm2 is not None else None

    passed, note, metrics = evaluate_liveness_challenge(challenge, pose1, pose2)

    all_results.append({
        "round": round_num,
        "challenge": challenge,
        "image_1": image1_path,
        "image_2": image2_path,
        "face_detected_img1": face1,
        "face_detected_img2": face2,
        "liveness_pass": bool(passed),
        "reason": "ok" if passed else note,
        "yaw_delta": metrics["yaw_delta"] if metrics else None,
        "pitch_delta": metrics["pitch_delta"] if metrics else None,
        "raw_score": metrics["raw_score"] if metrics else None
    })

# -----------------------------
# 6. Save outputs
# -----------------------------
df = pd.DataFrame(all_results)
df.to_csv(OUTPUT_CSV, index=False)

with open(OUTPUT_JSON, "w") as f:
    json.dump(all_results, f, indent=2)

# -----------------------------
# 7. Print summary
# -----------------------------
total_rounds = len(df)
passed_rounds = int(df["liveness_pass"].sum())
failed_rounds = total_rounds - passed_rounds
pass_rate = (passed_rounds / total_rounds * 100) if total_rounds > 0 else 0

print("========== LIVENESS SUMMARY ==========")
print(f"JSON file: {JSON_PATH}")
print(f"Total rounds: {total_rounds}")
print(f"Passed: {passed_rounds}")
print(f"Failed: {failed_rounds}")
print(f"Pass rate: {pass_rate:.2f}%")
print()
print("By challenge:")
print(df.groupby("challenge")["liveness_pass"].agg(["count", "sum"]))

print()
print(f"Saved CSV to:  {OUTPUT_CSV}")
print(f"Saved JSON to: {OUTPUT_JSON}")

display(df.head(10))

!pip install -q opencv-contrib-python matplotlib

SESSION_SUBDIR = "dark"

SESSION_SUBDIR = "glasses"

SESSION_SUBDIR = "normal"

# ============================================================
# LBPH + Bounding-Box Liveness Evaluation for Dataset Rounds
# Google Colab - One Cell Version
# Mirrors the Raspberry Pi run_liveness_check_lbph.py logic
# ============================================================

!pip install -q opencv-contrib-python-headless pandas

import json
import cv2
import numpy as np
import pandas as pd
from pathlib import Path
from google.colab import drive

# -----------------------------
# 1. Mount Google Drive
# -----------------------------
drive.mount('/content/drive')

# -----------------------------
# 2. CONFIG
# -----------------------------
BASE_DIR = Path("/content/drive/MyDrive/Capstone")

# Folder of Nathan training images
TRAIN_DIR = BASE_DIR / "dataset" / "nathan"

# Folder to evaluate: change to "normal", "dark", or "glasses"
SESSION_DIR = BASE_DIR / "dataset" / SESSION_SUBDIR

# Metadata file for the chosen dataset folder
METADATA_FILE = SESSION_DIR / "metadata.json"

# Output paths
OUTPUT_CSV = SESSION_DIR / f"lbph_liveness_{SESSION_SUBDIR}_results.csv"
OUTPUT_JSON = SESSION_DIR / f"lbph_liveness_{SESSION_SUBDIR}_results.json"

# LBPH model output paths
MODEL_DIR = BASE_DIR / "model" / "lbph"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

TRAINER_FILE = MODEL_DIR / "trainer.yml"
LABELS_FILE = MODEL_DIR / "labels.json"

# Haar cascade
CASCADE_PATH = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"

# Same style of thresholds as your Pi file
# Lower these if you want easier liveness passing
HORIZONTAL_THRESHOLD = 18
VERTICAL_THRESHOLD = 10

# LBPH confidence threshold: lower is better
LBPH_CONFIDENCE_THRESHOLD = 70.0

# Whether both images must contain a face
REQUIRE_FACE_IN_BOTH = True

# -----------------------------
# 3. Load detector
# -----------------------------
face_detector = cv2.CascadeClassifier(CASCADE_PATH)
if face_detector.empty():
    raise RuntimeError(f"Could not load Haar cascade: {CASCADE_PATH}")

# -----------------------------
# 4. Helper functions
# -----------------------------
def detect_largest_face_box(image_bgr):
    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

    faces = face_detector.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(80, 80)
    )

    if len(faces) == 0:
        return None

    faces = sorted(faces, key=lambda f: f[2] * f[3], reverse=True)
    return faces[0]


def face_center(face_box):
    x, y, w, h = face_box
    return (x + w / 2.0, y + h / 2.0)


def check_liveness(challenge, box1, box2):
    c1 = face_center(box1)
    c2 = face_center(box2)

    dx = c2[0] - c1[0]
    dy = c2[1] - c1[1]

    if challenge == "LOOK_LEFT":
        passed = dx <= -HORIZONTAL_THRESHOLD
    elif challenge == "LOOK_RIGHT":
        passed = dx >= HORIZONTAL_THRESHOLD
    elif challenge == "LOOK_UP":
        passed = dy <= -VERTICAL_THRESHOLD
    else:
        passed = False

    debug = {
        "movement_x": round(float(dx), 2),
        "movement_y": round(float(dy), 2),
        "face1_center": [round(float(c1[0]), 2), round(float(c1[1]), 2)],
        "face2_center": [round(float(c2[0]), 2), round(float(c2[1]), 2)],
    }

    return passed, debug


def crop_face(gray_image, face_box, padding=0.15):
    x, y, w, h = face_box
    img_h, img_w = gray_image.shape[:2]

    pad_w = int(w * padding)
    pad_h = int(h * padding)

    x1 = max(0, x - pad_w)
    y1 = max(0, y - pad_h)
    x2 = min(img_w, x + w + pad_w)
    y2 = min(img_h, y + h + pad_h)

    face = gray_image[y1:y2, x1:x2]
    if face.size == 0:
        raise ValueError("Face crop was empty")

    face = cv2.resize(face, (200, 200))
    return face


def resolve_to_session_file(image_path_str):
    # Metadata may contain Raspberry Pi absolute paths.
    # This maps them to the current Colab dataset folder by filename.
    return SESSION_DIR / Path(image_path_str).name


# -----------------------------
# 6. Authorization function
# -----------------------------
def authorize_first_image(image_bgr):
    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

    face_box = detect_largest_face_box(image_bgr)
    if face_box is None:
        return {
            "authorized": False,
            "reason": "no_face_for_authorization",
            "identity": None,
            "confidence": None,
            "predicted_label_id": None,
            "threshold": LBPH_CONFIDENCE_THRESHOLD,
        }

    face = crop_face(gray, face_box)
    label_id, confidence = recognizer.predict(face)

    identity = labels.get(str(label_id), "unknown")
    authorized = confidence <= LBPH_CONFIDENCE_THRESHOLD

    return {
        "authorized": bool(authorized),
        "reason": "ok" if authorized else "face_not_recognized",
        "identity": identity if authorized else "unknown",
        "predicted_label_id": int(label_id),
        "confidence": round(float(confidence), 4),
        "threshold": LBPH_CONFIDENCE_THRESHOLD,
    }

# -----------------------------
# 7. Load metadata
# -----------------------------
with open(METADATA_FILE, "r") as f:
    metadata = json.load(f)

rounds = metadata["rounds"]

# -----------------------------
# 8. Evaluate all rounds
# -----------------------------
all_results = []

for item in rounds:
    round_num = item.get("round")
    challenge = item.get("challenge")
    image1_path_str = item.get("image_1")
    image2_path_str = item.get("image_2")

    if not image1_path_str or not image2_path_str:
        all_results.append({
            "round": round_num,
            "challenge": challenge,
            "image_1": image1_path_str,
            "image_2": image2_path_str,
            "face_detected_img1": False,
            "face_detected_img2": False,
            "liveness_passed": False,
            "authorized": False,
            "identity": None,
            "confidence": None,
            "reason": "missing_image_path",
            "movement_x": None,
            "movement_y": None
        })
        continue

    img1_path = resolve_to_session_file(image1_path_str)
    img2_path = resolve_to_session_file(image2_path_str)

    img1 = cv2.imread(str(img1_path))
    img2 = cv2.imread(str(img2_path))

    if img1 is None or img2 is None:
        all_results.append({
            "round": round_num,
            "challenge": challenge,
            "image_1": str(img1_path),
            "image_2": str(img2_path),
            "face_detected_img1": False,
            "face_detected_img2": False,
            "liveness_passed": False,
            "authorized": False,
            "identity": None,
            "confidence": None,
            "reason": "could_not_read_image",
            "movement_x": None,
            "movement_y": None
        })
        continue

    box1 = detect_largest_face_box(img1)
    box2 = detect_largest_face_box(img2)

    face1 = box1 is not None
    face2 = box2 is not None

    if REQUIRE_FACE_IN_BOTH and (not face1 or not face2):
        all_results.append({
            "round": round_num,
            "challenge": challenge,
            "image_1": str(img1_path),
            "image_2": str(img2_path),
            "face_detected_img1": face1,
            "face_detected_img2": face2,
            "liveness_passed": False,
            "authorized": False,
            "identity": None,
            "confidence": None,
            "reason": "no_face_detected_in_one_or_both_images",
            "movement_x": None,
            "movement_y": None
        })
        continue

    liveness_passed, debug = check_liveness(challenge, box1, box2)

    if liveness_passed:
        auth_result = authorize_first_image(img1)
        reason = auth_result["reason"]
        authorized = auth_result["authorized"]
        identity = auth_result["identity"]
        confidence = auth_result["confidence"]
        predicted_label_id = auth_result["predicted_label_id"]
    else:
        reason = "challenge_failed"
        authorized = False
        identity = None
        confidence = None
        predicted_label_id = None

    all_results.append({
        "round": round_num,
        "challenge": challenge,
        "image_1": str(img1_path),
        "image_2": str(img2_path),
        "face_detected_img1": face1,
        "face_detected_img2": face2,
        "liveness_passed": bool(liveness_passed),
        "authorized": bool(authorized),
        "identity": identity,
        "predicted_label_id": predicted_label_id,
        "confidence": confidence,
        "threshold": LBPH_CONFIDENCE_THRESHOLD,
        "reason": reason,
        "movement_x": debug["movement_x"],
        "movement_y": debug["movement_y"],
        "face1_center": debug["face1_center"],
        "face2_center": debug["face2_center"],
    })

# -----------------------------
# 9. Save outputs
# -----------------------------
df = pd.DataFrame(all_results)
df.to_csv(OUTPUT_CSV, index=False)

with open(OUTPUT_JSON, "w") as f:
    json.dump(all_results, f, indent=2)

# -----------------------------
# 10. Print summary
# -----------------------------
total_rounds = len(df)
liveness_passes = int(df["liveness_passed"].sum()) if total_rounds > 0 else 0
authorized_passes = int(df["authorized"].sum()) if total_rounds > 0 else 0
liveness_failures = total_rounds - liveness_passes
authorization_failures = total_rounds - authorized_passes

liveness_pass_rate = (liveness_passes / total_rounds * 100) if total_rounds > 0 else 0
authorization_pass_rate = (authorized_passes / total_rounds * 100) if total_rounds > 0 else 0

print("========== LBPH + LIVENESS SUMMARY ==========")
print(f"Dataset folder: {SESSION_DIR}")
print(f"Total rounds: {total_rounds}")
print(f"Liveness passed: {liveness_passes}")
print(f"Liveness failed: {liveness_failures}")
print(f"Liveness pass rate: {liveness_pass_rate:.2f}%")
print()
print(f"Authorized passed: {authorized_passes}")
print(f"Authorized failed: {authorization_failures}")
print(f"Authorized pass rate: {authorization_pass_rate:.2f}%")
print()
print("By challenge:")
print(df.groupby("challenge")["liveness_passed"].agg(["count", "sum"]))
print()
print(f"Saved CSV to:  {OUTPUT_CSV}")
print(f"Saved JSON to: {OUTPUT_JSON}")
print()

display(df.head(20))