# -*- coding: utf-8 -*-
"""LBPH Liveness Detection (Testing Purposes)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVPsamQdLD_TohP3A_n6VxLxmUVnlxM4
"""

!pip install -q opencv-python matplotlib

from google.colab import drive
drive.mount('/content/drive')

import json
from pathlib import Path

import cv2
import matplotlib.pyplot as plt

BASE_DIR = Path("/content/drive/MyDrive/Capstone")

# Change this to the folder that contains round_021_img1.jpg and round_021_img2.jpg
SESSION_SUBDIR = Path("dataset") / "normal"

SESSION_DIR = BASE_DIR / SESSION_SUBDIR
METADATA_FILE = SESSION_DIR / "metadata.json"

IMG1_PATH = SESSION_DIR / "round_021_img1.jpg"
IMG2_PATH = SESSION_DIR / "round_021_img2.jpg"

CASCADE_PATH = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"

# Liveness thresholds
HORIZONTAL_THRESHOLD = 18
VERTICAL_THRESHOLD = 10

with open(METADATA_FILE, "r") as f:
    metadata = json.load(f)

face_detector = cv2.CascadeClassifier(CASCADE_PATH)

if face_detector.empty():
    raise RuntimeError(f"Could not load Haar cascade: {CASCADE_PATH}")

def show_image(title, image_bgr, figsize=(6,6)):
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=figsize)
    plt.imshow(image_rgb)
    plt.title(title)
    plt.axis("off")
    plt.show()


def detect_largest_face_box(image_bgr):
    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

    faces = face_detector.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(80, 80)
    )

    if len(faces) == 0:
        return None

    faces = sorted(faces, key=lambda f: f[2] * f[3], reverse=True)
    return faces[0]


def draw_face_box(image_bgr, face_box, color=(0, 255, 0)):
    boxed = image_bgr.copy()
    x, y, w, h = face_box
    cv2.rectangle(boxed, (x, y), (x + w, y + h), color, 3)
    return boxed


def face_center(face_box):
    x, y, w, h = face_box
    return (x + w / 2.0, y + h / 2.0)


def draw_center(image_bgr, center, color=(255, 0, 0)):
    marked = image_bgr.copy()
    cx, cy = int(center[0]), int(center[1])
    cv2.circle(marked, (cx, cy), 8, color, -1)
    return marked

round_21_info = None

for r in metadata["rounds"]:
    if r["round"] == 21:
        round_21_info = r
        break

if round_21_info is None:
    raise RuntimeError("Round 21 not found in metadata.")

challenge = round_21_info["challenge"]
challenge_text = round_21_info["challenge_text"]

print("Round:", round_21_info["round"])
print("Challenge:", challenge)
print("Challenge Text:", challenge_text)

img1 = cv2.imread(str(IMG1_PATH))
img2 = cv2.imread(str(IMG2_PATH))

if img1 is None:
    raise RuntimeError(f"Could not read {IMG1_PATH}")
if img2 is None:
    raise RuntimeError(f"Could not read {IMG2_PATH}")

show_image("Step 1: First Image (round_021_img1.jpg)", img1)
show_image("Step 2: Second Image (round_021_img2.jpg)", img2)

print("Image 1 shape:", img1.shape)
print("Image 2 shape:", img2.shape)

box1 = detect_largest_face_box(img1)
box2 = detect_largest_face_box(img2)

if box1 is None:
    raise RuntimeError("No face detected in image 1")
if box2 is None:
    raise RuntimeError("No face detected in image 2")

img1_boxed = draw_face_box(img1, box1)
img2_boxed = draw_face_box(img2, box2)

show_image("Step 3: Face Detection on Image 1", img1_boxed)
show_image("Step 4: Face Detection on Image 2", img2_boxed)

print("Face box 1:", box1)
print("Face box 2:", box2)

center1 = face_center(box1)
center2 = face_center(box2)

img1_centered = draw_center(img1_boxed, center1)
img2_centered = draw_center(img2_boxed, center2)

show_image("Step 5: Face Center in Image 1", img1_centered)
show_image("Step 6: Face Center in Image 2", img2_centered)

print("Face center 1:", center1)
print("Face center 2:", center2)

dx = center2[0] - center1[0]
dy = center2[1] - center1[1]

print("Step 7: Movement Calculation")
print("movement_x =", round(dx, 2))
print("movement_y =", round(dy, 2))

if challenge == "LOOK_LEFT":
    passed = dx <= -HORIZONTAL_THRESHOLD
elif challenge == "LOOK_RIGHT":
    passed = dx >= HORIZONTAL_THRESHOLD
elif challenge == "LOOK_UP":
    passed = dy <= -VERTICAL_THRESHOLD
else:
    passed = False

print("Step 8: Liveness Decision")
print("Challenge:", challenge_text)
print("Horizontal threshold:", HORIZONTAL_THRESHOLD)
print("Vertical threshold:", VERTICAL_THRESHOLD)
print("Liveness Passed:", passed)

final_img = img2_boxed.copy()

summary_text_1 = f"Challenge: {challenge_text}"
summary_text_2 = f"dx={dx:.2f}, dy={dy:.2f}"
summary_text_3 = f"Liveness Passed: {passed}"

cv2.putText(final_img, summary_text_1, (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 0), 2)
cv2.putText(final_img, summary_text_2, (20, 80), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 0), 2)
cv2.putText(final_img, summary_text_3, (20, 120), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0) if passed else (0, 0, 255), 2)

show_image("Step 9: Final Liveness Result", final_img, figsize=(8,6))