# -*- coding: utf-8 -*-
"""LBPH (Testing Purposes)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kkcl7H1qD-Jzts0MMg3bRS4ci8mdMWiY
"""

!pip install -q opencv-contrib-python

from google.colab import drive
drive.mount('/content/drive')

import json
from pathlib import Path

import cv2
import numpy as np

BASE_DIR = Path("/content/drive/MyDrive/Capstone")

# Nathan training folder
TRAIN_DIR = BASE_DIR / "dataset" / "nathan"

# Folder to test
TEST_SUBDIR = "khoi"   # change to "dark" or "glasses"
SESSION_DIR = BASE_DIR / "dataset" /TEST_SUBDIR
METADATA_FILE = SESSION_DIR / "metadata.json"

# Output folder
MODEL_DIR = BASE_DIR / "model" / "lbph"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

TRAINER_FILE = MODEL_DIR / "trainer.yml"
LABELS_FILE = MODEL_DIR / "labels.json"

CASCADE_PATH = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"

# LBPH: lower confidence is better
LBPH_CONFIDENCE_THRESHOLD = 70.0

face_detector = cv2.CascadeClassifier(CASCADE_PATH)

if face_detector.empty():
    raise RuntimeError(f"Could not load Haar cascade: {CASCADE_PATH}")

try:
    recognizer = cv2.face.LBPHFaceRecognizer_create(
        radius=1,
        neighbors=8,
        grid_x=8,
        grid_y=8
    )
except AttributeError:
    raise RuntimeError("cv2.face is not available. Make sure opencv-contrib-python installed.")

def detect_largest_face(gray_image):
    faces = face_detector.detectMultiScale(
        gray_image,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(80, 80)
    )

    if len(faces) == 0:
        return None

    faces = sorted(faces, key=lambda f: f[2] * f[3], reverse=True)
    return faces[0]


def crop_face(gray_image, face_box, padding=0.15):
    x, y, w, h = face_box
    img_h, img_w = gray_image.shape[:2]

    pad_w = int(w * padding)
    pad_h = int(h * padding)

    x1 = max(0, x - pad_w)
    y1 = max(0, y - pad_h)
    x2 = min(img_w, x + w + pad_w)
    y2 = min(img_h, y + h + pad_h)

    face = gray_image[y1:y2, x1:x2]

    if face.size == 0:
        raise ValueError("Face crop was empty")

    face = cv2.resize(face, (200, 200))
    return face

faces = []
label_ids = []
label_map = {"Nathan": 0}

valid_exts = {".jpg", ".jpeg", ".png"}

for image_path in sorted(TRAIN_DIR.iterdir()):
    if image_path.suffix.lower() not in valid_exts:
        continue

    image = cv2.imread(str(image_path))
    if image is None:
        print(f"[WARN] Could not read {image_path}")
        continue

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    face_box = detect_largest_face(gray)

    if face_box is None:
        print(f"[WARN] No face found in {image_path}")
        continue

    try:
        face = crop_face(gray, face_box)
        faces.append(face)
        label_ids.append(0)
    except Exception as e:
        print(f"[WARN] Failed on {image_path}: {e}")

if len(faces) == 0:
    raise RuntimeError("No usable Nathan training images found.")

recognizer.train(faces, np.array(label_ids))
recognizer.write(str(TRAINER_FILE))

id_to_name = {"0": "Nathan"}

with open(LABELS_FILE, "w") as f:
    json.dump(id_to_name, f, indent=2)

print(f"Trained on {len(faces)} images")
print("Saved:", TRAINER_FILE)
print("Saved:", LABELS_FILE)

with open(METADATA_FILE, "r") as f:
    metadata = json.load(f)

with open(LABELS_FILE, "r") as f:
    labels = json.load(f)

recognizer.read(str(TRAINER_FILE))

print("Session:", metadata["session"])
print("Rounds:", len(metadata["rounds"]))
print("Labels:", labels)

def resolve_to_session_file(image_path_str):
    filename = Path(image_path_str).name
    return SESSION_DIR / filename

def predict_authorized_lbph(image_path):
    image = cv2.imread(str(image_path))
    if image is None:
        return {
            "authorized": False,
            "identity": None,
            "confidence": None,
            "reason": "could_not_read_image"
        }

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    face_box = detect_largest_face(gray)

    if face_box is None:
        return {
            "authorized": False,
            "identity": None,
            "confidence": None,
            "reason": "no_face_detected"
        }

    try:
        face = crop_face(gray, face_box)
        label_id, confidence = recognizer.predict(face)

        identity = labels.get(str(label_id), "unknown")
        authorized = confidence <= LBPH_CONFIDENCE_THRESHOLD

        return {
            "authorized": bool(authorized),
            "identity": identity if authorized else "unknown",
            "closest_match": identity,
            "confidence": round(float(confidence), 4),
            "threshold": LBPH_CONFIDENCE_THRESHOLD,
            "reason": "ok" if authorized else "face_not_recognized"
        }
    except Exception as e:
        return {
            "authorized": False,
            "identity": None,
            "confidence": None,
            "reason": f"error: {e}"
        }

results = []

for round_info in metadata["rounds"]:
    image_1_path = resolve_to_session_file(round_info["image_1"])

    result = predict_authorized_lbph(image_1_path)

    results.append({
        "round": round_info["round"],
        "challenge": round_info["challenge"],
        "image_1": str(image_1_path),
        "authorized": result["authorized"],
        "identity": result["identity"],
        "closest_match": result.get("closest_match"),
        "confidence": result["confidence"],
        "threshold": result.get("threshold"),
        "reason": result["reason"]
    })

results[:5]

authorized_count = sum(1 for r in results if r["authorized"])
total_count = len(results)

print(f"Folder tested: {TEST_SUBDIR}")
print(f"Authorized passes: {authorized_count}/{total_count}\n")

for r in results:
    print(
        f'Round {r["round"]:03d} | '
        f'{r["challenge"]:10s} | '
        f'authorized={r["authorized"]} | '
        f'identity={r["identity"]} | '
        f'confidence={r["confidence"]} | '
        f'reason={r["reason"]}'
    )

OUTPUT_FILE = SESSION_DIR / f"lbph_results_{TEST_SUBDIR}.json"

with open(OUTPUT_FILE, "w") as f:
    json.dump(results, f, indent=2)

print("Saved:", OUTPUT_FILE)